alias zrc='vim ~/.zshrc && source ~/.zshrc'
alias vrc='vim ~/.vimrc'
alias gga='git add'
alias ggc='git commit -m'
alias ggl='git log --oneline --decorate --graph --all | less -FRX'
alias ggp='git push'
alias ggb='git branch | less -FRX'
alias ggs='git status'
alias ggsw='git switch'
alias ggco='git checkout'
alias python='python3 $@'
alias CC='gcc -Wall -Werror -Wall'
alias gglf='git ls-files'
alias exam='bash -c "$(curl https://grademe.fr)"'
alias cvrc='cat ~/.vimrc'
alias czsh='cat ~/.zshrc'
USER='user-name'
export USER
MAIL='user-name@student.42bcn.com'
export MAIL

